name: Release Build

on:
  workflow_dispatch:
    inputs:

env:
  GH_TOKEN: ${{ secrets.GIT_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.27'

      - name: Setup Environment
        run: |
          sudo ln -sf /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
          echo "date=$(/bin/date -u '+%d%m%Y%I%M')" >> $GITHUB_ENV
          git config --global user.name "neilchetty"
          git config --global user.email "neilchetty4559@gmail.com"

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .

      - name: Release
        run: |
          gh release create ${{ env.date }} 'build/bin/LibraryManagementSystem#LibraryManagementSystem' --generate-notes -t "Library Management System Release ${{ env.date }}"
